-- Written by the Alt Tracking Assistant Companion app. Do not edit by hand.
AltTrackingAssistantAppSync = {
    rev = 1791567839,
    characterMains = {
        ["characterMode"] = "classFaction",
        ["selections"] = {
            ["classFaction:WARRIOR:Alliance"] = "Player-100-0EEDD206",
            ["classFaction:DEMONHUNTER:Horde"] = "Player-100-0ED69519",
            ["classFaction:ROGUE:Horde"] = "Player-3675-0AFA5BD6",
            ["classFaction:DEMONHUNTER:Alliance"] = "Player-100-0ED628D2",
            ["classFaction:WARRIOR:Horde"] = "Player-100-0ECD28B4",
            ["classFaction:DEATHKNIGHT:Horde"] = "Player-100-0EEDD21E",
            ["classFaction:PRIEST:Horde"] = "Player-100-0ED69569",
            ["classFaction:EVOKER:Horde"] = "Player-100-0ED62F96",
            ["armor:mail"] = "Player-100-0EEDD223",
            ["classFaction:HUNTER:Alliance"] = "Player-100-0EEDD223",
            ["armor:cloth"] = "Player-100-0EEDDA4A",
            ["classFaction:MONK:Horde"] = "Player-100-0EEDDA3A",
            ["classFaction:MONK:Alliance"] = "Player-100-0EEDDA32",
            ["classFaction:ROGUE:Alliance"] = "Player-3675-0B010853",
            ["classFaction:SHAMAN:Horde"] = "Player-100-0EEDD22D",
            ["classFaction:WARLOCK:Alliance"] = "Player-100-0EEDDE6C",
            ["classFaction:PRIEST:Alliance"] = "Player-100-0EEDDA64",
            ["classFaction:PALADIN:Horde"] = "Player-100-0EEDD205",
            ["classFaction:HUNTER:Horde"] = "Player-100-0ED62F55",
            ["armor:plate"] = "Player-100-0EEDD219",
            ["classFaction:DEATHKNIGHT:Alliance"] = "Player-100-0ECCCF3E",
            ["classFaction:EVOKER:Alliance"] = "Player-100-0EEDD23B",
            ["classFaction:SHAMAN:Alliance"] = "Player-100-0ED62F84",
            ["classFaction:DRUID:Alliance"] = "Player-100-0EEDD969",
            ["classFaction:PALADIN:Alliance"] = "Player-100-0EEDD219",
            ["armor:leather"] = "Player-100-0ED628D2",
            ["trueMain"] = "Player-100-0EEDD219",
            ["classFaction:WARLOCK:Horde"] = "Player-100-0EEDDE5F",
            ["classFaction:MAGE:Alliance"] = "Player-100-0EEDDA4A",
            ["classFaction:DRUID:Horde"] = "Player-100-0EEDDC2B",
            ["classFaction:MAGE:Horde"] = "Player-100-0ED6951A",
        },
        ["trueMainEnabled"] = true,
        ["armorMode"] = "armor",
    },
    trackedItems = {
        ["shadowlands"] = {
            ["covenant"] = false,
            ["renown"] = true,
        },
    },
}
